[package]
name = "mid-player-broker"
version = "0.1.0"
authors = ["Divino G. de Menezes Neto <dgmneto@gmail.com>"]

[build-dependencies]
  prost-build = "0.4.0"

[dependencies]
  prost = "0.4.0"
  prost-derive = "0.4.0"
  bytes="0.4.11"
  tokio="0.1"
