kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: broker
  namespace: mid-player
  labels:
    app: mid-player-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mid-player-broker
    spec:
      containers:
      - name: mid-player-broker
        image: divinomenezes/mid-player-broker:0.0.1
        imagePullPolicy: Always
        ports:
        - name: broker
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 400M
